numpy

In [1]:
import numpy as np

In [3]:
big_list = list(range(100000))
big_array = np.arange(100000)

In [4]:
%timeit [x**2 for x in big_list]

5.08 ms ± 21 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit big_array **2

46 μs ± 589 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


#creating arrays

In [6]:
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [10]:
b = np.array([[1,2,3,4],[5,6,7,8]])#2-D array
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
a = np.array([0,0,0,0])
print(a)

[0 0 0 0]


In [13]:
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
print(np.ones((2,3)))  

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
print(np.full((2,3),7))


[[7 7 7]
 [7 7 7]]


In [18]:
import numpy as np  
print(np.arange(0, 10, 2))  

[0 2 4 6 8]


In [19]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
rng = np.random.default_rng(seed = 42)
print(rng.random((2,3)))

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [23]:
print(rng.integers(1,10,size = (3,3)))

[[7 7 7]
 [8 5 2]
 [8 5 5]]


In [27]:
print(rng.normal(loc = 0 ,scale = 1, size = 5))

[ 0.77779194  0.0660307   1.12724121  0.46750934 -0.85929246]


#Array attributes and data types

In [29]:
M = np.array([[1,2,3],[4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
print(M.shape)

(2, 3)


In [30]:
print(M.size)

6


In [31]:
print(M.dtype)

int64


In [35]:
ints = np.array([1,2,3],dtype = np.int32)



In [36]:
ints.dtype

dtype('int32')

In [39]:
floats = np.array([1,2,3],dtype = np.float64)
floats.dtype

dtype('float64')

#indexing and slicing

In [40]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
print(x[0])

10


In [42]:
print(x[5])

15


In [43]:
M = np.arange(1,13).reshape(3,4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
print(M[1,2])

7


In [47]:
M[1]

array([5, 6, 7, 8])

In [48]:
print(M[:,1])

[ 2  6 10]


In [49]:
print(M[:,0])

[1 5 9]


#Vector operation

In [50]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(a)


[1 2 3 4]


In [51]:
print(b)

[10 20 30 40]


In [52]:
print(a+b)

[11 22 33 44]


In [53]:
print(a*b)


[ 10  40  90 160]


#Broadcasting

In [54]:
a = np.array([1,2,3])
b = 10

In [55]:
print(a+b)

[11 12 13]


In [59]:
a = np.array([[1,2,3],
              [4,5,6]])  
a.shape

(2, 3)

In [60]:
b = np.array([10,20,30])
b.shape

(3,)

In [61]:
print(a+b)

[[11 22 33]
 [14 25 36]]
